"""Add user_agent to page_visits

Revision ID: 21aa2c41d5b7
Revises: 683b1fa0e139
Create Date: 2025-05-23 16:20:13.686592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21aa2c41d5b7'
down_revision: Union[str, None] = '683b1fa0e139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_visits', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_visits', 'user_agent')
    # ### end Alembic commands ###
